import '@/globals.scss'
import { Providers } from '@/providers'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function OnboardingLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='font-mainFont'>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
